---
# This playbook will create database and users for remote login
- name: create database
  mysql_db:
    login_user: root
    login_password: {{ lookup('cypher','secret=secret/MYSSQL_ROOT_PASSWORD') }}
    name: "{{ morpheus['customOptions']['databaseName'] }}"
    state: present

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user: login_user: root login_password: {{ lookup('cypher','secret=secret/MYSSQL_ROOT_PASSWORD') }} name={{ morpheus['customOptions']['databaseUserName'] }} password={{ morpheus['customOptions']['databasePassword'] }} priv=*.*:ALL,GRANT host='%' state=present
  
- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user: login_user: root login_password: {{ lookup('cypher','secret=secret/MYSSQL_ROOT_PASSWORD') }} name={{ morpheus['customOptions']['databaseUserName'] }} password={{ morpheus['customOptions']['databasePassword'] }} priv=*.*:ALL,GRANT host='localhost' state=present
